const COFFEE_STRIPE_ID = "price_1MbRtsKNb1HN7WsmD9KgbMVU"
const SUNGLASSES_STRIPE_ID = "price_1MbRxrKNb1HN7Wsmtx9qQdWj"
const CAMERA_STRIPE_ID = "price_1MbRyNKNb1HN7WsmYWOHsOUO"
const STRIPE_CHECKOUT_URL = `http://localhost:4000/checkout`

export { COFFEE_STRIPE_ID, SUNGLASSES_STRIPE_ID, CAMERA_STRIPE_ID, STRIPE_CHECKOUT_URL }
